name: Validate Signature

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact from latest main
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          branch: main
          name: signature-validation-windows
          check_artifacts: true
          search_artifacts: true

      - name: Run validation
        run: |
          .\signature-validation.exe
