name: Validate Signature

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download artifact from latest main
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          branch: main
          name: signature-validation-windows
          check_artifacts: true
          search_artifacts: true

      - name: Run validation and push results
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $output = .\signature-validation.exe
          $output | Write-Output
          
          # Sign the commit with GitHub's key by using the GitHub API
          $bytes = [System.Text.Encoding]::UTF8.GetBytes($output)
          $content = [Convert]::ToBase64String($bytes)
          
          # Get the current SHA if the file exists
          $sha = ""
          try {
            $resp = gh api "repos/${{ github.repository }}/contents/status.json?ref=validation-results" | ConvertFrom-Json
            $sha = $resp.sha
          } catch {
            Write-Host "File status.json does not exist yet or branch validation-results does not exist."
          }

          # Update status file
          if ($sha) {
            gh api --method PUT "repos/${{ github.repository }}/contents/status.json" `
              -f message="Set validation result" `
              -f content="$content" `
              -f branch="validation-results" `
              -f sha="$sha"
          } else {
            gh api --method PUT "repos/${{ github.repository }}/contents/status.json" `
              -f message="Set validation result" `
              -f content="$content" `
              -f branch="validation-results"
          }
